Fix TypeError on install
This fixes the following traceback that arises when installing the add-on
for the first time, an issue that was introduced with #9

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 689, in __call__
  Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 454, in install_product
  Module Products.GenericSetup.tool, line 405, in runAllImportStepsFromProfile
   - __traceback_info__: profile-png.lims:default
  Module Products.GenericSetup.tool, line 1511, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1323, in _doRunImportStep
   - __traceback_info__: senaite.abx.setup_handler
  Module senaite.abx.setuphandlers, line 54, in setup_handler
  Module senaite.abx.setuphandlers, line 159, in setup_antibiotics
  Module senaite.abx.content.antibiotic, line 169, in setAntibioticClass
TypeError: 'NoneType' object is not callable
```